### 1. Registrar Nuevo Usuario
POST http://localhost:8000/register
Content-Type: application/json

{
  "name": "Admin Pruebas",
  "email": "admintest@example.com",
  "password": "password123",
  "role": "admin"
}

### 2. Iniciar Sesión (Login)
POST http://localhost:8000/login
Content-Type: application/json

{
  "email": "admin1@example.com",
  "password": "password123"
}

### 3. Cerrar Sesión (Logout) 
POST http://localhost:8000/logout
Authorization: Bearer 7962a966c3b6d0bffaa07724f9c51bd2
Content-Type: application/json

### 4. Listar Todos los Usuarios 
GET http://localhost:8000/users
Authorization: Bearer 7962a966c3b6d0bffaa07724f9c51bd2
Content-Type: application/json

### 5. Actualizar un Usuario 
PUT http://localhost:8000/users/1
Authorization: Bearer 7962a966c3b6d0bffaa07724f9c51bd2
Content-Type: application/json

{
  "name": "Juan Gestor Actualizado",
  "role": "gestor"
}
### 6. Eliminar un Usuario 
DELETE http://localhost:8000/users/2
Authorization: Bearer 7962a966c3b6d0bffaa07724f9c51bd2
Content-Type: application/json
{
  "name": "Prueba",
  "role": "admin"
}